# Generated by Django 5.1.3 on 2024-11-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf_content',
            field=models.URLField(blank=True, null=True),
        ),
    ]
